### ISSUE TITLE
Problem with copying volumetric mesh

### ISSUE THREAD

**Issue by AlirezaSharif** [SVMTK/SVMTK#25]
I encountered a problem when trying to make a copy of my volumetric mesh using "copy.deepcopy" command in Python and got this error: "TypeError: can't pickle SVMTK.Domain objects". In my case, I need to retrieve my original mesh to remove another subdomain from it.
Is there any way to copy the volumetric mesh or any functionality to add several volumetric subdomains (similar to remove_subdomain) to make the original volumetric mesh (just a quick note that I am using the docker version of SVMTK)?

**Comment by larsmva** [comment]
Hi! 

It is not possible to load or deepcopy SVMKT.Domain. This is because SVMKT.Domain uses pointers to CGAL class, which has disabled copy constructor and assignment operator. 

However, you can remove subdomains when using meshio to change mesh format: 
```python 
# meshio version 4.3.2
import meshio
#Load mesh 
mesh = meshio.read("test.mesh")
# Extract points, tetrahedrons and subdomain tags
points = mesh.points
cells = mesh.cells_dict["tetra"] 
tags  = mesh.cell_data_dict["medit:ref"]["tetra"]
# Remove subdomain marked with tag = 1
remove_subdomain=1
tetra = cells[tags!=remove_subdomain]
subdomains = tags[tags!=remove_subdomain]
# Unconnected points are removed in meshio
new_mesh = meshio.Mesh(points, {"tetra": tetra}, cell_data={"subdomains": [subdomains]})
meshio.write("removed_subdomain.xdmf", new_mesh)
```

**Comment by AlirezaSharif** [comment]
Hi Lars!

Awesome. That solved my problem. Many thanks!
