### ISSUE TITLE
cgal=5.3.0 not available in releases

### ISSUE THREAD

**Issue by MeryemABBAD** [SVMTK/SVMTK#27]
Hello, 

I am trying to install SVMTK, but cgal=5.3.0 is not available in releases. ( I get an error when I run: git checkout releases/CGAL-5.3.0). Also, when I try to build the docker image from dockerfile, I get an issue with the cgal release version. 

Do you know what might be the issue ?

Thank you very much ! 

Meryem

**Comment by larsmva** [comment]
Hi, 

It seems that CGAL changed the branch name to v5.3.

Lars
