### ISSUE TITLE
Adding additional labels to mesh

### ISSUE THREAD

**Issue by AlirezaSharif** [SVMTK/SVMTK#30]
Hi, 

I wanted to add additional labels to my SVMTK-generated mesh based on some masks of subdomains. One way is to generate the surface mesh of these masks and generate the volumetric mesh using SVMTK. However, this method forces the mesh to be conforming at the boundaries of subdomains, which is problematic when the masks are not perfect.

The other option that I was pursuing was using Salome platform, which allows me to add this kind of labels quite easily. Be that as it may, Salome can only import mesh tags via .med format. To this end, I tried converting the  .mesh format to .med using Meshio, but still, Salome cannot import the mesh tags. I just wanted to know whether you have any experience regarding this issue or any solution you may propose.
I have attached the code I am using for conversion:
```python
# Read the .mesh file into meshio. 
mesh = meshio.read("SVMTK_generated.mesh")
# Extract subdomains and boundaries between regions into appropriate containers.
points = mesh.points
tetra  = {"tetra": mesh.cells_dict["tetra"]}
subdomains = {"subdomains": [mesh.cell_data_dict["medit:ref"]["tetra"]]}
# Write the subdomains of the mesh.
MED = meshio.Mesh(points, tetra, cell_data=subdomains)
meshio.write("cell_tags.med", MED)

```

Thank you in advance.

**Comment by larsmva** [comment]
Hi,

I don't have any experience with salome, so I can't help you there. 

There are other options to importing additional labels, but that requires a mapping between the masks and the coordinates system of the mesh. If that is available, then you could look at [Link](https://link.springer.com/content/pdf/10.1007/978-3-030-95136-8_4.pdf) for more details.

Hope you find it useful! 

Cheers 
Lars

**Comment by AlirezaSharif** [comment]
Hi Lars,
Thank you so much for sharing this. It actually solved my problem!
